spring.application.name=RAG-Ecommerce-Support

#OLLAMA - used for both embeddings and final answer
# ==================================================================
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=phi4-mini
spring.ai.ollama.chat.options.num-context=8192
spring.ai.ollama.embedding.options.model=nomic-embed-text
# ====================================================================

#Pinecone
spring.ai.vectorstore.pinecone.api-key=${PINECONE_API_KEY}
spring.ai.vectorstore.pinecone.index-name=teva-support-768
spring.ai.vectorstore.pinecone.namespace=policydocs